version: "3.8"
   
services:
  db:
    image: sqlite3
    volumes:
      - ./data/db:/var/lib/sqlite3/data
    environment:
      - SQLITE3_DB=oc-lettings-site
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/website
    ports:
      - "8000:8000"
    depends_on:
      - db